#!/usr/bin/python3

from flask import Flask, render_template

app = Flask(__name__)

@app.route('/number_odd_or_even/<int:n>')
def number_odd_or_even(n):
    result = "even" if n % 2 == 0 else "odd"
    return render_template('number.html', number=n, result=result)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001)

